name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      env: 
        NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
        GOOGLE_ID: ${{secrets.GOOGLE_ID}}
        NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
        NEXTAUTH_URL_INTERNAL: ${{secrets.NEXTAUTH_URL_INTERNAL}}
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build application
      run: npm run build
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
